### PR TITLE
Create CMakeLists.txt

### PR DESCRIPTION
**Pull request by alextwothousand**
I've added a CMakeLists.txt file, as I (among many others) use CMake as their build system.

I created a new branch called master-3, just to prevent clashes with the changes made in the v4 branch.

### CODE REVIEW

**Comment by alextwothousand** [comment]
(If it would be possible for you to do so, could you merge this as a separate branch called master-3? I prefer the API of libmem v3, :L)

**Comment by rdbo** [comment]
I'll take a look at CMake and learn how it works before adding support. Seems really interesting, especially for this project. Again, I really don't recommend getting too used to V3, as V4 will have all of its capabilities, a lot of fixes, more features, better practices, etc.

**Comment by alextwothousand** [comment]
Bit too late for that 😂
I'll make some sort of compatibility layer for both version's API if need be.

**Comment by rdbo** [comment]
Done: 07dced3c0356e2ecb8f3298360a335275db0da85

**Pull request closed without merging**
